# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DkGeokoder
                                 A QGIS plugin
 This plugin uses DAWA to geocode Danish addresses with QGIS processing framework
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-06
        copyright            : (C) 2019 by Septima
        email                : asger@septima.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Septima'
__date__ = '2019-09-06'
__copyright__ = '(C) 2019 by Septima'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DkGeokoder class from file DkGeokoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dkgeokoder import DkGeokoderPlugin
    return DkGeokoderPlugin()
