# -*- coding: utf-8 -*-

"""
/***************************************************************************
 DkAddressTools
                                 A QGIS plugin
 This plugin provides tools to work with Danish addresses within the QGIS processing framework
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-09-06
        copyright            : (C) 2019 by Septima
        email                : asger@septima.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Septima'
__date__ = '2019-09-06'
__copyright__ = '(C) 2019 by Septima'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QMetaType
from qgis.core import (QgsProcessing,
                       QgsCoordinateReferenceSystem,
                       QgsExpression,
                       QgsFeature, 
                       QgsGeometry, 
                       QgsField,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterExpression,
                       QgsProcessingParameterFeatureSink,
                       QgsWkbTypes)
from .addresstoolsdk_api import AdresseVaelgerClient, ADGANGSPUNKT_CRS

# Attributes from Adressevælgerens opslag-med-id, added to the wash result in AdresseVaelgerClient.geocode().
# Field types use QMetaType.Type (not QVariant.Type) since the latter's type enum is gone under Qt6/PyQt6.
ENRICHED_FIELDS = [
    ("adresse_id", QMetaType.Type.QString, 40),
    ("adresse_betegnelse", QMetaType.Type.QString, 0),
    ("etage", QMetaType.Type.QString, 10),
    ("dor", QMetaType.Type.QString, 10),
    ("adresse_status", QMetaType.Type.QString, 5),
    ("husnummer_id", QMetaType.Type.QString, 40),
    ("husnummertekst", QMetaType.Type.QString, 10),
    ("adgangsadressebetegnelse", QMetaType.Type.QString, 0),
    ("vejnavn", QMetaType.Type.QString, 0),
    ("husnummer_status", QMetaType.Type.QString, 5),
    ("postnr", QMetaType.Type.QString, 4),
    ("postnummer_navn", QMetaType.Type.QString, 0),
    ("kommunekode", QMetaType.Type.QString, 4),
    ("vejkode", QMetaType.Type.QString, 4),
    ("supplerende_bynavn", QMetaType.Type.QString, 0),
]



class DkGeokoderAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT_KVALITET1 = 'OUTPUT_KVALITET1'
    OUTPUT_KVALITET2 = 'OUTPUT_KVALITET2'
    OUTPUT_KVALITET3 = 'OUTPUT_KVALITET3'
    OUTPUT_FEJL = 'OUTPUT_FEJL'
    INPUT = 'INPUT'
    EXPRESSION = 'EXPRESSION'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input adressedata'),
                [QgsProcessing.TypeVector]
            )
        )

        self.addParameter(
            QgsProcessingParameterExpression(
                self.EXPRESSION,
                self.tr('Adresse-udtryk'),
                parentLayerParameterName = self.INPUT
            )
        )

        # Adressevask-svar splittes op i fire lag efter vaskestatus_kode, så resultaterne kan
        # kvalitetsvurderes og håndteres forskelligt nedstrøms.
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_KVALITET1,
                self.tr('Kvalitet 1 (kode 1000)')
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_KVALITET2,
                self.tr('Kvalitet 2 (kode 900)')
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_KVALITET3,
                self.tr('Kvalitet 3 (kode 700/800)')
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_FEJL,
                self.tr('Fejl (koder < 0')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        exp = self.parameterAsExpression(parameters, "EXPRESSION", context)

        status_kode_field_name = self.tr("vaskestatus_kode")
        status_tekst_field_name = self.tr("vaskestatus_tekst")
        historisk_denote_field_name = self.tr("historisk_adressebetegnelse")
        historisk_fra_field_name = self.tr("historisk_virkningfra")
        historisk_til_field_name = self.tr("historisk_virkningtil")
        fields = source.fields()
        for name, field_type, length in ENRICHED_FIELDS:
            fields.append(QgsField(self.tr(name), field_type, len=length) if length else QgsField(self.tr(name), field_type))
        fields.append(QgsField(status_kode_field_name, QMetaType.Type.Int))
        fields.append(QgsField(status_tekst_field_name, QMetaType.Type.QString))
        fields.append(QgsField(historisk_denote_field_name, QMetaType.Type.QString))
        fields.append(QgsField(historisk_fra_field_name, QMetaType.Type.QString))
        fields.append(QgsField(historisk_til_field_name, QMetaType.Type.QString))
        
        (sink_kvalitet1, dest_id_kvalitet1) = self.parameterAsSink(parameters, self.OUTPUT_KVALITET1,
                context, fields, QgsWkbTypes.Point, QgsCoordinateReferenceSystem(ADGANGSPUNKT_CRS))
        (sink_kvalitet2, dest_id_kvalitet2) = self.parameterAsSink(parameters, self.OUTPUT_KVALITET2,
                context, fields, QgsWkbTypes.Point, QgsCoordinateReferenceSystem(ADGANGSPUNKT_CRS))
        (sink_kvalitet3, dest_id_kvalitet3) = self.parameterAsSink(parameters, self.OUTPUT_KVALITET3,
                context, fields, QgsWkbTypes.Point, QgsCoordinateReferenceSystem(ADGANGSPUNKT_CRS))
        (sink_fejl, dest_id_fejl) = self.parameterAsSink(parameters, self.OUTPUT_FEJL,
                context, fields, QgsWkbTypes.Point, QgsCoordinateReferenceSystem(ADGANGSPUNKT_CRS))

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()
        exp_context = context.expressionContext()
        exp_context.appendScope(source.createExpressionContextScope())
        expression = QgsExpression(exp)
        expression.prepare(exp_context)

        geocoder = AdresseVaelgerClient()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break
            # Copy src feat to dest feat
            out_feature = QgsFeature(fields)
            for field in source.fields():
                out_feature[field.name()] = feature[field.name()]
            
            # Get address string    
            exp_context.setFeature(feature)
            address = expression.evaluate(exp_context)

            # Geocode it
            geocoded = geocoder.geocode(address)
            kode = geocoded["vaskestatus_kode"] if geocoded else None
            if geocoded:
                out_feature[status_kode_field_name] = geocoded["vaskestatus_kode"]
                out_feature[status_tekst_field_name] = geocoded["vaskestatus_tekst"]
                for name, _, _ in ENRICHED_FIELDS:
                    out_feature[self.tr(name)] = geocoded.get(name)
                out_feature[historisk_denote_field_name] = geocoded["historisk_adressebetegnelse"]
                out_feature[historisk_fra_field_name] = geocoded["historisk_virkningfra"]
                out_feature[historisk_til_field_name] = geocoded["historisk_virkningtil"]
                # accesspoint requires the (separate) opslag-med-id call to have succeeded too
                if geocoded["accesspoint"]:
                    out_feature.setGeometry(QgsGeometry(geocoded["accesspoint"]))

            # Route the feature to its quality-tier sink based on vaskestatus_kode
            if kode == 1000:
                sink_kvalitet1.addFeature(out_feature, QgsFeatureSink.FastInsert)
            elif kode == 900:
                sink_kvalitet2.addFeature(out_feature, QgsFeatureSink.FastInsert)
            elif kode in (700, 800):
                sink_kvalitet3.addFeature(out_feature, QgsFeatureSink.FastInsert)
            else:
                sink_fejl.addFeature(out_feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {
            self.OUTPUT_KVALITET1: dest_id_kvalitet1,
            self.OUTPUT_KVALITET2: dest_id_kvalitet2,
            self.OUTPUT_KVALITET3: dest_id_kvalitet3,
            self.OUTPUT_FEJL: dest_id_fejl,
        }

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Geokod danske adresser med Adressevask'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Geokodning'

    def shortDescription(self):
        return self.helpString()

    def helpString(self):
        return self.tr("""
        <p>
            Denne algoritme er udviklet af <a href="https://www.septima.dk">Septima</a> og anvender Klimadatastyrelsens 
            <a href="https://confluence.kds.dk/display/ADV/Adressevask">Adressevask</a>- og 
            <a href="https://confluence.kds.dk/pages/viewpage.action?pageId=246743156">Adressevælger</a>-API'er.
        </p>
        <p>
            Med pluginet kan man oversætte en ustruktureret adressetekst til en officiel adresse fra Danmarks Adresseregister (DAR). 
            Det håndterer stavefejl og situationer, hvor den officielle adressebetegnelse er ændret.
        </p>
        <p>
            Pluginet tager imod en adressetekst og returnerer dén adresse, som bedst matcher. Hvis adresseteksten, som skal geokodes, 
            findes i flere felter i attributtabellen (fx vejnavn i et felt, husnummer i et andet felt og postnummer i et tredje felt), 
            så skal disse sættes sammen til et samlet adresseudtryk vha. udtryksbyggeren (klik på epsilon-ikonet). 
        </p>
        <p>
            Algoritmen vasker adressen og slår den herefter op hos Adressevælger i samme kald, så outputtet indeholder både 
            adresse-id og den fulde mængde af adresseoplysninger (vejnavn, postnummer, kommunekode, adgangspunktets koordinater m.m.) - 
            der er ikke brug for et separat opslagsværktøj.
        </p>
        <p>
            En gyldig adresse kan skrives på forskellige måder (varianter). Man kan fx vælge at udelade det supplerende bynavn, 
            eller at bruge det forkortede "adresseringsvejnavn" i stedet for det fulde vejnavn. 
        </p>
        <p>
            Adressevask svar angiver hvor sikkert svaret er, i form af en <b>vaskestatus</b>-kode og -tekst, der erstatter DAWAs gamle 
            A/B/C-kategorier. Positive koder (fx 1000, 900, 800, 700) indikerer en eller anden grad af match, negative koder betyder 
            at adressen ikke kunne vaskes. Vaskestatus_kode og vaskestatus_tekst sættes altid på outputtet, også når adressen ikke 
            kunne vaskes - i så fald er de øvrige adressefelter og geometrien tomme.
        </p>
        <p>
            Resultaterne fordeles på fire outputlag efter vaskestatus_kode, så de kan kvalitetsvurderes hver for sig: 
            <b>Kvalitet 1</b> (kode 1000, eksakt match), <b>Kvalitet 2</b> (kode 900, tilnærmet vejnavn), 
            <b>Kvalitet 3</b> (kode 700/800, interval-adresse) og <b>Fejl</b> (negativ kode, eller ingen adresse at vaske).
        </p>
        <p>
            Adressevask anvender også DAR’s historiske adresser som datagrundlag, således at adresser som er ændret også kan vaskes. 
            Matcher adresseteksten en historisk adressebetegnelse, angives den tidligere adressebetegnelse i feltet 
            <b>historisk_adressebetegnelse</b>, mens de øvrige felter altid indeholder adressens aktuelle betegnelse og oplysninger.
        </p>
        <p>
            Koordinaterne for adgangspunktet leveres i ETRS89 / UTM zone 32N (EPSG:25832).
        </p>
        <p>
            Læs mere på <a href="https://github.com/Septima/qgis-addresstoolsdk">pluginets GitHub-side</a>, hvor du også kan se et eksempel på anvendelse.
        </p>
        """)

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DkGeokoderAlgorithm()
